spring:
  application:
    name: hhc-control-plane
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
server:
  shutdown: graceful

