apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - control-plane.yaml
  - runtime-worker.yaml
  - network-policy.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: hyperhealth-connect
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
    includeTemplates: true
